### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by jamesle-0812** [j1rie/STM32F103-bootloader#1]
Hi there, recently I'm keen on uploading a firmware thru usb on a custom stm32f103 board. I had a look on your project, very interesting. However, you've not clarified a situation of using your project, or at least binary files. Please have a look the link below as a reference 
[https://github.com/dhylands/stm32-test/tree/master/board-STM32F103-Mini](url)
Besides, you've said in the linker script file is 
> Linker script for STM32F103C8, 128K flash, 20K RAM.

I'm pretty sure f103c8 only has 64K flash, although it should be fine without modify.
Please let me know your opinion. Thanks!

**Comment by j1rie** [comment]
Does https://github.com/j1rie/IRMP_STM32#flashing-the-firmware answer your question?
The specs say  STM32F103C8 has 64k flash, in reality it's 128k.

**Comment by jamesle-0812** [comment]
Hi, thanks for your reply. Can you little bit explain please? In my case, I'd love to flash a simple firmware (blink led) to stm32f103 thru usb. What I need to do if using your bootloader? Which framework I should use for the blink led code? Many thanks!

**Comment by j1rie** [comment]
The only requirement needed is to let your code start from APP_ADDRESS (https://github.com/j1rie/STM32F103-bootloader/blob/master/usbdfu.c#L30).

**Comment by jamesle-0812** [comment]
You mean I should put an address to the file in your cmt, compile it to get .bin file and then upload it thru ST-link/USB-to-TTL converter. How about use it? Do I need to change any jumper on my board? Do I miss anything? I'm new to stm32 family uC so I'm sorry if annoying!

**Comment by j1rie** [comment]
Yes. And no need for a jumper. The bootloader waits, if download happens, if not it starts the application. For download use dfu-util with the wait option https://sourceforge.net/p/dfu-util/dfu-util/ci/3133d5367095cd41acc5b2e539d16fd14f354e89/.

**Comment by jamesle-0812** [comment]
Thanks for your reply. What is your recommendation for app address to optimize flash memory? About the jumper, just to make it clear, after setting boot0 to 1, boot1 to 0 for programming mode and then uploading code, I should leave it jumper like that even if upload in the next time!

**Comment by j1rie** [comment]
See https://github.com/j1rie/STM32F103-bootloader/blob/master/config.h and https://github.com/j1rie/IRMP_STM32_KBD/wiki/Herstellungsprozess-Schwarze#pins-und-boot0-einl%C3%B6ten. 0x08002000 and BOOT0 0.
